### ISSUE TITLE
 0.61 Unable to work

### ISSUE THREAD

**Issue by quan0zhou** [Redth/dotnet-maui-check#72]
**.Net version 6.0.0-preview.6.21355.2**
###  **maui-check does not work**
![image](https://user-images.githubusercontent.com/27860834/126424383-dc118950-e326-4cfc-8824-fd75fe3da806.png)
![image](https://user-images.githubusercontent.com/27860834/126424410-825da4f2-f95f-4542-bba4-7ddd37379222.png)

**Comment by quan0zhou** [comment]
Download the source code, modify the configuration to NET 6.0 run the source code
![image](https://user-images.githubusercontent.com/27860834/126437321-d71b8bfd-3b4e-4be3-a62e-446383fc7fcc.png)

**Comment by alexivkin** [comment]
at devs: What's the thinking behind having the tool run on 5.0 when maui itself is only available on 6.0?
Why not have it pre-built for 6?

**Comment by bddckr** [comment]
Bootstrapping issues comes to mind? How can you run a tool that installs (among other things) the SDK for which it requires the runtime of already?

**Comment by quan0zhou** [comment]
But it is not backward compatible

**Comment by alexivkin** [comment]
Wrong assumptions. Why would one ever expect or trust a third party tool to update the SDK? MS clearly stated everywhere tha you need 6.0, so installing it manually is the natural first step. 

The real issue for me is that maui-check does not work in the dotnet docker container v6 because SDK docker images have the only one SDK and can't/shouldn't have more than one.

**Comment by bddckr** [comment]
> Why would one ever expect or trust a third party tool to update the SDK?

Because that's 50% of what this tool does. It checks, and allows you to fix up all missing components by installing them. That includes the SDK. Microsoft is using this tool to do exactly that themselves (see [here](https://github.com/dotnet/maui-samples/blob/714460431541f40570e91225e8ba4bc1fe08025f/azure-pipelines.yml#L33-L34)). Whether or not you trust that is another question, but by now this is off-topic so I'll exit this issue.

---

On backwards compatibility: I stand corrected - minor and patch releases seem to be compatible for a given major release only. As such the .NET 6 runtime is not compatible with the .NET 5 one this tool requires.

I imagine targeting .NET 5 is done as it's the latest supported production-ready version of .NET. Requiring a .NET 6 runtime to be installed already forces any user of this tool to first install a .NET 6 preview - something this tool is helping with in the first place. While you can install other components as well with `maui-check`, Microsoft, my CI and my colleagues are using it to keep up with the latest previews and as such it would break this ability. Changing to require .NET 6 to run `maui-check` would break all those users.

**Comment by Redth** [comment]
Part of the problem is, if I allow maui-check to run _on_ .NET 6, it has issues installing updates and changing .NET 6.  So, for now it requires .NET 3.1 or 5.0.
